### ISSUE TITLE
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

### ISSUE THREAD

**Issue by manwe-pl** [crocs-muni/roca#23]
```
Traceback (most recent call last):
  File "./roca-detect", line 11, in <module>
    load_entry_point('roca-detect==1.0.5', 'console_scripts', 'roca-detect')()
  File "/home/xxxxx/.local/lib64/python3.4/site-packages/roca/detect.py", line 1782, in main
    app.mainxxxxx
  File "/home/xxxxx/.local/lib64/python3.4/site-packages/roca/detect.py", line 1777, in main
    self.work()
  File "/home/xxxxx/.local/lib64/python3.4/site-packages/roca/detect.py", line 1675, in work
    ret = self.process_inputs()
  File "/home/xxxxx/.local/lib64/python3.4/site-packages/roca/detect.py", line 691, in process_inputs
    sub = self.process_file(data, fname)
  File "/home/xxxxx/.local/lib64/python3.4/site-packages/roca/detect.py", line 779, in process_file
    ret.append(self.process_pkcs7(data, name))
  File "/home/xxxxx/.local/lib64/python3.4/site-packages/roca/detect.py", line 1605, in process_pkcs7
    is_pem = data.startswith('-----')
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

I've tried changing `data.startswith('-----')` to `data.startswith(b'-----')`, but got another error:
```
  File "/home/xxxxx/.local/lib64/python3.4/site-packages/roca/detect.py", line 1606, in process_pkcs7
    if re.match(r'^[a-zA-Z0-9-\s+=/]+$', data):
  File "/usr/lib64/python3.4/re.py", line 160, in match
    return _compile(pattern, flags).match(string)
TypeError: can't use a string pattern on a bytes-like object
```

**Comment by nealmcb** [comment]
The current code works with Python 2.7.13. Not with 2.7.6, or with Python 3.
The README.md shows how to use Docker, or pyenv to get 2.7.13 (or any other Python version).

Getting it working with Python 3 is an important enhancement request.

**Comment by manwe-pl** [comment]
README.md states `It won't work with lower Python version.`, so I've used my system's default 3.4. But OK, I've changed it to `pip2.7 install` and it works fine now. Thank you.

**Comment by ph4r05** [comment]
I agree py3 compatibility is imporant feature request! :)

**Comment by eli-schwartz** [comment]
What.

Why does the setup.py list the classifiers:
```
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
```
If none of that is actually true?

It is the easiest way to quickly check which version of python something is meant for. :disappointed:

Also setuptools allows you to mark which versions of python are compatible...
