### ISSUE TITLE
Vulnerable certificates in tests not detected

### ISSUE THREAD

**Issue by danky78** [crocs-muni/roca#51]
With the latest 1.2.11, the certificates under tests failed when trying to get the STREET_ADDRESS attribute and they are not detected:

14:09:58 02 jbiosca@alien ~/roca/rocacheck/roca-detect/roca-master/roca  
python3 detect.py --debug tests/data/cert04.pem 
2018-03-02 14:09:59 [12274] DEBUG processing tests/data/cert04.pem as PEM
2018-03-02 14:10:00 [12274] DEBUG PEM processing failed: type object 'NameOID' has no attribute 'STREET_ADDRESS'
2018-03-02 14:10:00 [12274] DEBUG type object 'NameOID' has no attribute 'STREET_ADDRESS'
2018-03-02 14:10:00 [12274] DEBUG Traceback (most recent call last):
  File "detect.py", line 1288, in process_pem_cert
    return self.process_x509(x509, name=name, idx=idx, data=data, pem=True, source='pem-cert')
  File "detect.py", line 1403, in process_x509
    js['subject'] = utf8ize(try_get_dn_string(x509.subject, shorten=True))
  File "detect.py", line 250, in try_get_dn_string
    NameOID.STREET_ADDRESS: "St",
AttributeError: type object 'NameOID' has no attribute 'STREET_ADDRESS'

2018-03-02 14:10:00 [12274] INFO ### SUMMARY ####################
2018-03-02 14:10:00 [12274] INFO Records tested: 0
2018-03-02 14:10:00 [12274] INFO .. PEM certs: . . . 1
2018-03-02 14:10:00 [12274] INFO .. DER certs: . . . 0
2018-03-02 14:10:00 [12274] INFO .. RSA key files: . 0
2018-03-02 14:10:00 [12274] INFO .. PGP master keys: 0
2018-03-02 14:10:00 [12274] INFO .. PGP total keys:  0
2018-03-02 14:10:00 [12274] INFO .. SSH keys:  . . . 0
2018-03-02 14:10:00 [12274] INFO .. APK keys:  . . . 0
2018-03-02 14:10:00 [12274] INFO .. JSON keys: . . . 0
2018-03-02 14:10:00 [12274] INFO .. LDIFF certs: . . 0
2018-03-02 14:10:00 [12274] INFO .. JKS certs: . . . 0
2018-03-02 14:10:00 [12274] INFO .. PKCS7: . . . . . 0
2018-03-02 14:10:00 [12274] DEBUG . Total RSA keys . 1  (# of keys RSA extracted & analyzed)
2018-03-02 14:10:00 [12274] INFO No fingerprinted keys found (OK)
2018-03-02 14:10:00 [12274] INFO ################################

Withouth --debug there are not warnings or errors and they appear to be valid.

**Comment by danky78** [comment]
It seems that some OIDS are missing in module cryptography 1.2.3 that comes with my ubuntu 16.04
I upgraded to cryptography 1.2.4 and now its ok.

Maybe you should put the OIDs inside the try in order to not mark the vulnerable certificates as ok with older releases of cryptography.

**Comment by ph4r05** [comment]
I will add minimal requirement 1.2.4 for the cryptography module. Thanks for info!

**Comment by ph4r05** [comment]
fix in v1.2.12
